# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'SwiftExample' do
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', '~> 3.0'
pod 'JSQMessagesViewController', :path => '../'

end

target 'SwiftExampleTests' do
pod 'JSQMessagesViewController', :path => '../'
end
